### ISSUE TITLE
Hello Maria

### ISSUE THREAD

**Issue by hiddenpearls** [mariash/Wordpress-Plugin-Related-Posts-Thumbnails#2]
Hello Maria,

I am Adnan and noticed that this plugin is not updated more than 2 years. I have developed Analytify 
https://wordpress.org/plugins/wp-analytify/ and is interested to take over this plugin at WordPress.org 

Can you please allow me to work with you on this plugin ? 

Thanks in Advance.
waiting to hearing from you.

Cheers!
http://adnan.pk/about

**Comment by hiddenpearls** [comment]
Still waiting to hear from you @mariash

**Comment by mariash** [comment]
Hi Adhan,

Thanks for your suggestion. Please feel free to open PRs right here. 

Thanks, 
Maria

**Comment by hiddenpearls** [comment]
Ok Thanks @mariash

**Comment by hiddenpearls** [comment]
hey @mariash 

I noticed, It has been a year and I have not worked on it. Well, I am working on it now and sending updated version very soon that is compatible with PHP7.0.0 and WP 4.4 ;)

Stay tuned.

Cheers
Adnan

**Comment by mariash** [comment]
Hi Adhan, that would be great! Thank you. Please let me know your website, so I can link you in contributors list. Cheers, Maria

**Comment by hiddenpearls** [comment]
@mariash 

http://adnan.pk/

I am pushing updates at my fork repo https://github.com/hiddenpearls/Wordpress-Plugin-Related-Posts-Thumbnails

**Comment by hiddenpearls** [comment]
and will send Pull request When It is ready.

**Comment by hiddenpearls** [comment]
@mariash Accept my pull request please.

**Comment by hiddenpearls** [comment]
@mariash I was going to work on it today but saw previous work is not yet integrated. 

May I hear from you please ?

**Comment by mariash** [comment]
@hiddenpearls, thanks for pr, I'll take a look when I get back from vacation.

cheers,
Maria

**Comment by hiddenpearls** [comment]
@mariash Alright - I will wait :+1:

**Comment by mariash** [comment]
PR for this issue: https://github.com/mariash/Wordpress-Plugin-Related-Posts-Thumbnails/pull/3

Thanks Adnan for your contribution!

**Comment by hiddenpearls** [comment]
@mariash Happy to give it a life :100: 
will do more now as you are back from vacations now. hope you enjoyed  your time.
